name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 更新するバージョン
        required: true
        default: minor
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  production_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up
        uses: ./.github/actions/setup

      - name: Update version
        run: |
          git config --local user.name "actions-user"
          git config --local user.email "action@github.com"
          npm version ${{ github.event.inputs.type }} -m "chore: update version [skip ci]"

      - name: Deploy to Production Environment
        uses: ./.github/actions/deployment
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          environment: production

      - name: Push changes
        run: git push --follow-tags

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCRIPT_PATH: .github/workflows/createRelease.sh
        run: |
          chmod u+x $SCRIPT_PATH
          ./$SCRIPT_PATH
